"""KernelBench interop: export kernel-gym challenges into KernelBench's task format.

KernelBench (https://github.com/ScalingIntelligence/KernelBench) frames each task as a
Python module defining:

  * `class Model(nn.Module)`   — the reference computation in eager PyTorch,
  * `get_inputs()`             — list of tensors passed to `Model.forward`,
  * `get_init_inputs()`        — list of args passed to `Model.__init__` (usually []),
  * `class ModelNew(nn.Module)`— a custom (Triton/CUDA) implementation with the same
                                 forward signature.

Its harness runs ModelNew vs Model for correctness (allclose over several seeds) and times
both for a speedup; tasks are grouped into `level`s by difficulty.

kernel-gym's `Challenge` carries the same two computations — `reference()` (pure PyTorch)
and `solution()` (Triton) — plus `make_inputs()`. This module rewrites a Challenge into a
self-contained KernelBench task file:

  * Model.forward    wraps challenge.reference()
  * ModelNew.forward wraps challenge.solution()
  * get_inputs()     calls the challenge's make_inputs(preset, 'cuda', dtype) at runtime and
                     returns just the tensor args, in forward order
  * non-tensor challenge args (eps, causal, window, reduction, sm_scale, ...) are baked into
    the module as constructor state so forward() takes only tensors.

Level mapping (kernel-gym tier -> KernelBench level):  tier 1-2 -> 1, tier 3 -> 2, tier 4-5 -> 3.

The emitted files import triton (via the challenge module's `from gym.tri import ...`) and
therefore only *run* on a CUDA box, like the rest of kernel-gym. Export itself needs no GPU:
we call make_inputs on CPU purely to learn which args are tensors vs scalars.
"""

from __future__ import annotations

import inspect
import json
import os
import string

import torch

from . import registry
from .registry import Challenge

# Repo root: gym/kernelbench.py -> gym/ -> <repo root> (which holds challenges/ and gym/).
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def level_for_tier(tier: int) -> int:
    """kernel-gym tier -> KernelBench level. 1-2 -> 1, 3 -> 2, 4-5 -> 3."""
    if tier <= 2:
        return 1
    if tier == 3:
        return 2
    return 3


_TEMPLATE = string.Template('''\
"""KernelBench-format export of kernel-gym $cid — $cname.

Auto-generated by gym/kernelbench.py (`python -m gym export`). Do not edit by hand.

KernelBench level $level  (kernel-gym tier $tier, preset "$preset", dtype $dtype).
`Model` wraps the challenge's eager-PyTorch reference(); `ModelNew` wraps its Triton
solution(). Non-tensor challenge args are baked in as constructor state so forward()
takes only tensors, matching the KernelBench task shape. Runs on a CUDA GPU only
(Triton has no CPU/macOS backend).
"""

import sys

import torch
import torch.nn as nn

sys.path.insert(0, r"$repo_root")

from $module import reference as _kg_reference
from $module import solution as _kg_solution
from $module import make_inputs as _kg_make_inputs

level = $level


class Model(nn.Module):
    """Eager PyTorch reference computation (kernel-gym reference())."""

    def __init__(self):
        super().__init__()
        self.scalars = $scalars

    def forward(self, $params):
        kwargs = {$kwitems}
        kwargs.update(self.scalars)
        return _kg_reference(**kwargs)


class ModelNew(nn.Module):
    """Custom Triton implementation (kernel-gym solution())."""

    def __init__(self):
        super().__init__()
        self.scalars = $scalars

    def forward(self, $params):
        kwargs = {$kwitems}
        kwargs.update(self.scalars)
        return _kg_solution(**kwargs)


def get_inputs():
    d = _kg_make_inputs("$preset", "cuda", $dtype)
    return [d[k] for k in $keys]


def get_init_inputs():
    return []
''')


def _split_inputs(ch: Challenge, preset: str, dtype: torch.dtype):
    """Return (tensor_keys, scalars) by building the inputs once on CPU.

    Tensors -> forward arguments (get_inputs order); everything else -> baked constructor
    state. CPU allocation works on any machine, so this needs no GPU.
    """
    inputs = ch.make_inputs(preset, "cpu", dtype)
    tensor_keys = [k for k, v in inputs.items() if torch.is_tensor(v)]
    scalars = {k: v for k, v in inputs.items() if not torch.is_tensor(v)}
    return tensor_keys, scalars


def render(ch: Challenge, preset: str | None = None) -> tuple[str, dict]:
    """Render the KernelBench task source for `ch`. Returns (source_text, meta)."""
    if preset is None or preset not in ch.presets:
        preset = next(iter(ch.presets))
    dtype = ch.dtypes[0]
    module = inspect.getmodule(ch.solution).__name__
    tensor_keys, scalars = _split_inputs(ch, preset, dtype)
    level = level_for_tier(ch.tier)

    params = ", ".join(tensor_keys)
    kwitems = ", ".join(f'"{k}": {k}' for k in tensor_keys)
    keys = "[" + ", ".join(f'"{k}"' for k in tensor_keys) + "]"
    scalars_src = "{" + ", ".join(f'"{k}": {v!r}' for k, v in scalars.items()) + "}"

    src = _TEMPLATE.substitute(
        cid=ch.id, cname=ch.name, level=level, tier=ch.tier, preset=preset,
        dtype=str(dtype), repo_root=_REPO_ROOT, module=module,
        scalars=scalars_src, params=params, kwitems=kwitems, keys=keys,
    )
    meta = {"id": ch.id, "name": ch.name, "level": level, "tier": ch.tier,
            "preset": preset, "dtype": str(dtype)}
    return src, meta


def to_kernelbench(ch: Challenge, out_dir: str, preset: str | None = None) -> dict:
    """Emit one KernelBench task file for `ch` under out_dir/level{N}/{id}.py.

    Returns a manifest entry {id, name, level, tier, file, ...}; `file` is relative to out_dir.
    """
    src, meta = render(ch, preset)
    level_dir = os.path.join(out_dir, f"level{meta['level']}")
    os.makedirs(level_dir, exist_ok=True)
    rel = os.path.join(f"level{meta['level']}", f"{ch.id}.py")
    path = os.path.join(out_dir, rel)
    with open(path, "w") as f:
        f.write(src)
    meta["file"] = rel
    return meta


def export_all(out_dir: str, preset: str | None = None) -> list[dict]:
    """Export every registered challenge and write out_dir/manifest.json.

    Returns the manifest (list of entries, sorted by id).
    """
    os.makedirs(out_dir, exist_ok=True)
    manifest = [to_kernelbench(ch, out_dir, preset)
                for ch in registry.load_all().values()]
    manifest.sort(key=lambda m: m["id"])
    with open(os.path.join(out_dir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    return manifest
